"""Carapace SDK v0.5.0 — Portable Trust Envelope for AI Agents"""

from .enforce import (
    CapabilityDenied,
    CardExpired,
    CardLike,
    EnforcementPolicy,
    enforce,
    enforce_all,
    enforce_any,
    has_capability,
    require_capability,
)
from .expiry import (
    ExpiryStatus,
    check_expiry,
    is_expired,
    make_expires_at,
    parse_expires_at,
    time_remaining,
    validate_expiry_for_verify,
)
from .versioning import (
    OwnerMismatchError,
    SupersedesNotFoundError,
    VersionChain,
    VersionChainError,
    VersionEntry,
    VersionSequenceError,
    prepare_version_fields,
    validate_supersedes_registration,
    validate_version_chain,
)
from .delegation import (
    CapabilityEscalation,
    DelegationChainBroken,
    DelegationError,
    DelegationExpired,
    DelegationSigningError,
    DelegationToken,
    DelegationVerifyResult,
    DelegatorCardInvalid,
    InMemoryNonceRegistry,
    RedelegationDepthExceeded,
    ReplayDetected,
    SignatureInvalid,
    TTLExceedsDelegator,
    create_delegation,
    enforce_delegated,
    narrow_capabilities,
    redelegate,
    validate_capability_subset,
    verify_delegation,
    verify_delegation_chain,
)

from .protected_paths import (
    DEFAULT_PROTECTED_PATTERNS,
    UNAUTHORIZED_SOURCES,
    ApprovalSourceForbidden,
    AuditLogEntry,
    ProtectedPathError,
    ProtectedWriteApproval,
    ProtectedWriteBlocked,
    check_protected_write,
    clear_audit_log,
    get_audit_log,
    is_protected_path,
    register_audit_sink,
)
from .epistemic import (
    GENESIS_HASH,
    ConfidenceLevel,
    EpistemicEntry,
    EpistemicLog,
    Source,
    hash_data,
)
from .compliance import (
    BUILTIN_PROFILES,
    ComplianceProfile,
    ComplianceResult,
    ComplianceViolation,
    evaluate_compliance,
)
from .escalation import (
    INDUSTRIAL_ESCALATION_POLICY,
    EscalationDenied,
    EscalationPolicy,
    EscalationRequest,
    EscalationRequired,
    EscalationStatus,
    EscalationTimedOut,
    EscalationTrigger,
    EscalationUrgency,
    check_all_escalations,
    check_escalation,
)

from .catalog import (
    CatalogEntry,
    CatalogState,
    GateResult,
    fetch_catalog,
    run_gate_check,
)
from .receipt import (
    create_receipt,
    post_receipt,
    post_receipt_async,
    verify_receipt,
)

__version__ = "0.5.0"

__all__ = [
    # enforce
    "CapabilityDenied",
    "CardExpired",
    "CardLike",
    "EnforcementPolicy",
    "enforce",
    "enforce_all",
    "enforce_any",
    "has_capability",
    "require_capability",
    # expiry
    "ExpiryStatus",
    "check_expiry",
    "is_expired",
    "make_expires_at",
    "parse_expires_at",
    "time_remaining",
    "validate_expiry_for_verify",
    # versioning
    "OwnerMismatchError",
    "SupersedesNotFoundError",
    "VersionChain",
    "VersionChainError",
    "VersionEntry",
    "VersionSequenceError",
    "prepare_version_fields",
    "validate_supersedes_registration",
    "validate_version_chain",
    # delegation
    "CapabilityEscalation",
    "DelegationChainBroken",
    "DelegationError",
    "DelegationExpired",
    "DelegationSigningError",
    "DelegationToken",
    "DelegationVerifyResult",
    "DelegatorCardInvalid",
    "InMemoryNonceRegistry",
    "RedelegationDepthExceeded",
    "ReplayDetected",
    "SignatureInvalid",
    "TTLExceedsDelegator",
    "create_delegation",
    "enforce_delegated",
    "narrow_capabilities",
    "redelegate",
    "validate_capability_subset",
    "verify_delegation",
    "verify_delegation_chain",
    # protected paths
    "DEFAULT_PROTECTED_PATTERNS",
    "UNAUTHORIZED_SOURCES",
    "ApprovalSourceForbidden",
    "AuditLogEntry",
    "ProtectedPathError",
    "ProtectedWriteApproval",
    "ProtectedWriteBlocked",
    "check_protected_write",
    "clear_audit_log",
    "get_audit_log",
    "is_protected_path",
    "register_audit_sink",
    # epistemic
    "GENESIS_HASH",
    "ConfidenceLevel",
    "EpistemicEntry",
    "EpistemicLog",
    "Source",
    "hash_data",
    # compliance
    "BUILTIN_PROFILES",
    "ComplianceProfile",
    "ComplianceResult",
    "ComplianceViolation",
    "evaluate_compliance",
    # escalation
    "INDUSTRIAL_ESCALATION_POLICY",
    "EscalationDenied",
    "EscalationPolicy",
    "EscalationRequest",
    "EscalationRequired",
    "EscalationStatus",
    "EscalationTimedOut",
    "EscalationTrigger",
    "EscalationUrgency",
    "check_all_escalations",
    "check_escalation",
    # v0.5.0 — catalog
    "CatalogEntry",
    "CatalogState",
    "GateResult",
    "fetch_catalog",
    "run_gate_check",
    # v0.5.0 — receipts
    "create_receipt",
    "post_receipt",
    "post_receipt_async",
    "verify_receipt",
]
